name: lpprinter
description: LP priter flutter plugin
version: 0.0.1
author: wang qi
homepage: https://github.com/wangmarkqi/LPPrinter_plugin.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.lpprinter
        pluginClass: LpprinterPlugin

